import Head from 'next/head';

export default function Home() {
  return (
    <div className="bg-background">
      <Head>
        <title>Marko Djuric Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      {/* <Navbar /> */}

      {/* Header */}

      {/* About Me */}

      {/* Where I've Worked */}

      {/* Projects */}

      {/* Get in Touch */}
    </div>
  );
}
