import Head from 'next/head';

export default function Home() {
  return (
    <>
      <section className="bg-background pb-28 mx-auto flex flex-col justify-center md:min-w-0 lg:min-w-[1000px] hoverable">
        <Head>
          <title>Marko Djuric Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1 className="text-primary font-SpaceMono mb-2 md:mb-5">Hi, my name is</h1>
        <h2 className="text-gray-200 font-bold text-4xl md:text-6xl lg:text-7xl mb-3 md:mb-6">Marko Đurić.</h2>
        <h3 className="text-gray-400 font-bold text-4xl md:text-6xl lg:text-7xl mb-4 md:mb-8">I build things for the web.</h3>
        <p className="text-gray-400 max-w-2xl text-md lg:text-lg">
          I'm a software engineer specializing in building web applications which helps people do their everyday work easier. Currently I'm focused on
          building in house specialized products at{' '}
          <a className="underline decoration-primary" href="https://www.compassholding.net/" target="_blank">
            Compass Holding
          </a>
          .
        </p>
      </section>
    </>
  );
}
